### ISSUE TITLE
Missing mysql files

### ISSUE THREAD

**Issue by ghost** [remcodezwart/upload.it#1]
Hi @remcodezwart,

I understand you know longer working on this repository, but can you kindly add the mysql scripts uploads etc?

**Comment by ghost** [comment]
@remcodezwart Submitting these would really help me.

**Comment by remcodezwart** [comment]
Alright I will submit them today/tommorow

**Comment by ghost** [comment]
Thank you, you are amazing! epic project additions by the way!

**Comment by remcodezwart** [comment]
Added the sql files the default users are the same as huge
