### ISSUE TITLE
[QUESTION] Quota

### ISSUE THREAD

**Issue by ghost** [remcodezwart/upload.it#2]
Hi @remcodezwart,

May I ask how would you handle quota within this app giving specific users specific upload limit quotas?

**Comment by remcodezwart** [comment]
That itsn't taken into account at all if you want to have that you would have to build it yourself

**Comment by remcodezwart** [comment]
There is a limit to file size though

 if ($_FILES["file"]["size"] > 500000) {
            return false;
            exit();
        } 

found in the userModel
line 357

**Comment by ghost** [comment]
Thanks @remcodezwart
